# Jekyll configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'The Modrich Travel Blog'
description: "Stories and experiences from our occasional travels"

short_url: 'lucasmodrich.github.io/'
#google_analytics: UA-69281367-1
#disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
#baseurl: "/blog/"

destination: docs

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - node_modules
  - .git
  - .gitignore