baseURL = "http://lucasmodrich.github.io/"
languageCode = "en-us"
defaultContentLanugage = "en"

title = "The Modrich Blog"
##theme = "hugo-casper3"
##theme = "meghna-hugo"
theme = "persian-hugo"
publishDir = "docs"

[params]
  description = "Thoughts, things and life..."
  author = "Lucas Modrich"
  disableLanguageSwitchButton = true
  